### ISSUE TITLE
Unable to access account data. 

### ISSUE THREAD

**Issue by garrettMarsh1** [tylerebowers/Schwab-API-Python#31]
I am unable to access acount data currently, the market data endpoints are functioning as expected. 
It was working for me earlier this week. Possible Schwab made some changes on their end. 

logs:

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.schwabapi.com:443
DEBUG:urllib3.connectionpool:https://api.schwabapi.com:443 "POST /v1/oauth/token HTTP/11" 200 705
INFO:schwab_client:Schwab client initialized
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.schwabapi.com:443
DEBUG:urllib3.connectionpool:https://api.schwabapi.com:443 "GET /trader/v1/accounts/accountNumbers HTTP/11" 404 94
ERROR:schwab_client:Failed to retrieve linked accounts. Status code: 404
ERROR:schwab_client:Response content: 404 Not Found: Requested route ('traderapi-accounts.apigx-origin.schwab.com') does not exist.

ERROR:schwab_order_manager:Failed to retrieve linked accounts.
Traceback (most recent call last):
  File "d:\CodeProjects\SchwabDashboard\main.py", line 121, in <module>
    asyncio.run(main())
  File "C:\Users\GARRE\.conda\envs\openbb_env\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\GARRE\.conda\envs\openbb_env\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GARRE\.conda\envs\openbb_env\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "d:\CodeProjects\SchwabDashboard\main.py", line 24, in main
    await order_manager.initialize()
  File "d:\CodeProjects\SchwabDashboard\order_manager.py", line 18, in initialize
    self.account_hash = await self.get_account_hash()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\CodeProjects\SchwabDashboard\order_manager.py", line 42, in get_account_hash
    raise Exception("Failed to retrieve linked accounts.")
Exception: Failed to retrieve linked accounts.

**Comment by tylerebowers** [comment]
Around 11pm est last night the api was down (probably for some maintenence). As you can see "404 Not Found: Requested route ('traderapi-accounts.apigx-origin.schwab.com') does not exist."

It is now working.
